version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    build: .
    env_file:
      - ./.env
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=seuncodes
      - MONGO_INITDB_ROOT_PASSWORD=seuncodes
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis

volumes:
  mongo-db:
